// Curated list of common 5-letter words — the daily ANSWER pool (the word of
// the day is WORDS[dayIndex % WORDS.length]). Guess VALIDATION uses the much
// larger allowed.ts dictionary; this list is also accepted, so every possible
// answer is always guessable. Keep these common/fair — order/length only
// affect the daily rotation.
//
// All entries are exactly 5 lowercase letters, no proper nouns.
export const WORDS: string[] = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone',
  'along', 'alter', 'among', 'anger', 'angle', 'angry', 'apart', 'apple', 'apply', 'arena',
  'argue', 'arise', 'array', 'aside', 'asset', 'audio', 'audit', 'avoid', 'award', 'aware',
  'badly', 'baker', 'basic', 'beach', 'began', 'begin', 'being', 'below', 'bench', 'birth',
  'black', 'blade', 'blame', 'blank', 'blast', 'blind', 'block', 'blood', 'board', 'boast',
  'bonus', 'boost', 'booth', 'bound', 'brain', 'brand', 'brass', 'brave', 'bread', 'break',
  'breed', 'brick', 'brief', 'bring', 'broad', 'broke', 'brown', 'brush', 'build', 'built',
  'bunch', 'burst', 'buyer', 'cabin', 'cable', 'candy', 'cargo', 'carry', 'catch', 'cause',
  'chain', 'chair', 'chalk', 'chaos', 'charm', 'chart', 'chase', 'cheap', 'cheat', 'check',
  'chess', 'chest', 'chief', 'child', 'chill', 'chose', 'civic', 'civil', 'claim', 'class',
  'clean', 'clear', 'click', 'cliff', 'climb', 'clock', 'close', 'cloth', 'cloud', 'coach',
  'coast', 'could', 'count', 'court', 'cover', 'crack', 'craft', 'crash', 'crazy', 'cream',
  'crime', 'crisp', 'cross', 'crowd', 'crown', 'crude', 'curve', 'cycle', 'daily', 'dance',
  'dealt', 'death', 'debut', 'delay', 'depth', 'doing', 'doubt', 'dozen', 'draft', 'drama',
  'drank', 'dream', 'dress', 'dried', 'drill', 'drink', 'drive', 'drove', 'eager', 'eagle',
  'early', 'earth', 'eight', 'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal',
  'error', 'event', 'every', 'exact', 'exist', 'extra', 'faith', 'false', 'fault', 'favor',
  'feast', 'fence', 'fever', 'fewer', 'field', 'fifth', 'fifty', 'fight', 'final', 'first',
  'fixed', 'flame', 'flash', 'fleet', 'flesh', 'float', 'flood', 'floor', 'flour', 'fluid',
  'focus', 'force', 'forth', 'forty', 'forum', 'found', 'frame', 'frank', 'fraud', 'fresh',
  'front', 'frost', 'fruit', 'fully', 'funny', 'ghost', 'giant', 'given', 'glass', 'globe',
  'glory', 'going', 'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp',
  'grass', 'grave', 'great', 'green', 'greet', 'grief', 'gross', 'group', 'grown', 'guard',
  'guess', 'guest', 'guide', 'happy', 'harsh', 'heart', 'heavy', 'hello', 'hence', 'hobby',
  'honor', 'horse', 'hotel', 'house', 'human', 'humor', 'hurry', 'ideal', 'image', 'imply',
  'index', 'inner', 'input', 'irony', 'issue', 'ivory', 'joint', 'judge', 'juice', 'knife',
  'knock', 'known', 'label', 'labor', 'large', 'laser', 'later', 'laugh', 'layer', 'learn',
  'lease', 'least', 'leave', 'legal', 'lemon', 'level', 'light', 'limit', 'local', 'logic',
  'loose', 'lover', 'lower', 'loyal', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker',
  'march', 'match', 'maybe', 'mayor', 'meant', 'medal', 'media', 'mercy', 'metal', 'meter',
  'might', 'minor', 'minus', 'mixed', 'model', 'money', 'month', 'moral', 'motor', 'mount',
  'mouse', 'mouth', 'movie', 'music', 'naive', 'naked', 'nasty', 'naval', 'nerve', 'never',
  'newly', 'night', 'noble', 'noise', 'north', 'novel', 'nurse', 'ocean', 'offer', 'often',
  'olive', 'onion', 'opera', 'orbit', 'order', 'organ', 'other', 'ought', 'outer', 'owner',
  'paint', 'panel', 'paper', 'party', 'pasta', 'patch', 'pause', 'peace', 'pearl', 'phase',
  'phone', 'photo', 'piano', 'piece', 'pilot', 'pitch', 'place', 'plain', 'plane', 'plant',
  'plate', 'plaza', 'point', 'pound', 'power', 'press', 'price', 'pride', 'prime', 'print',
  'prior', 'prize', 'probe', 'proof', 'proud', 'prove', 'pulse', 'punch', 'pupil', 'queen',
  'query', 'quest', 'queue', 'quick', 'quiet', 'quite', 'quota', 'quote', 'radar', 'radio',
  'raise', 'rally', 'range', 'rapid', 'ratio', 'reach', 'react', 'ready', 'realm', 'rebel',
  'refer', 'relax', 'reply', 'rider', 'ridge', 'right', 'rigid', 'rival', 'river', 'roast',
  'robot', 'rocky', 'rough', 'round', 'route', 'royal', 'rugby', 'rural', 'sadly', 'saint',
  'salad', 'sauce', 'scale', 'scare', 'scene', 'scope', 'score', 'sense', 'serve', 'seven',
  'shade', 'shake', 'shall', 'shame', 'shape', 'share', 'shark', 'sharp', 'sheep', 'sheet',
  'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shoot', 'shore', 'short', 'shown',
  'sight', 'silly', 'since', 'sixth', 'sixty', 'skill', 'slate', 'sleep', 'slice', 'slide',
  'slope', 'small', 'smart', 'smile', 'smoke', 'snake', 'solar', 'solid', 'solve', 'sorry',
  'sound', 'south', 'space', 'spare', 'speak', 'speed', 'spell', 'spend', 'spent', 'spice',
  'spike', 'spine', 'split', 'spoke', 'sport', 'spray', 'squad', 'stack', 'staff', 'stage',
  'stain', 'stair', 'stake', 'stand', 'stark', 'start', 'state', 'steam', 'steel', 'steep',
  'steer', 'stern', 'stick', 'still', 'stock', 'stone', 'stood', 'stool', 'store', 'storm',
  'story', 'stove', 'strap', 'straw', 'strip', 'study', 'stuff', 'style', 'sugar', 'suite',
  'sunny', 'super', 'surge', 'sweet', 'swept', 'swift', 'swing', 'sword', 'table', 'taken',
  'taste', 'teach', 'teeth', 'tempo', 'tenth', 'thank', 'theft', 'their', 'theme', 'there',
  'these', 'thick', 'thief', 'thigh', 'thing', 'think', 'third', 'those', 'three', 'threw',
  'throw', 'thumb', 'tiger', 'tight', 'tired', 'title', 'toast', 'today', 'token', 'tooth',
  'topic', 'total', 'touch', 'tough', 'towel', 'tower', 'trace', 'track', 'trade', 'trail',
  'train', 'trait', 'trash', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried', 'troop',
  'truck', 'truly', 'trunk', 'trust', 'truth', 'twice', 'twist', 'ultra', 'uncle', 'under',
  'undue', 'union', 'unite', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual',
  'valid', 'value', 'vapor', 'vault', 'venue', 'verse', 'video', 'virus', 'visit', 'vital',
  'vivid', 'vocal', 'voice', 'voter', 'wagon', 'waste', 'watch', 'water', 'weary', 'weigh',
  'weird', 'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'white', 'whole', 'whose',
  'witch', 'woman', 'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'wrist',
  'write', 'wrong', 'wrote', 'yield', 'young', 'youth',
]

/** Fast membership set for guess validation. */
export const WORD_SET: ReadonlySet<string> = new Set(WORDS)
